[package]
name = "binacle"
version = "1.0.0"
authors = ["Guillaume Jeanne"]

[dependencies]
memmap = "0.5.2"
rustc-serialize = "*"
docopt = "*"
fs2 = "*"
walkdir = "*"
time = "*"
fast-math = "*"
regex = "*"
